### ISSUE TITLE
Query about ~ symbol in ASJP

### ISSUE THREAD

**Issue by theroonba** [lexibank/asjp#11]
As far as I recall, ~ represents a marker to denote that the 2 previous sounds are combined as one phoneme.

For instance kh~a is segmented as 'kh','a' (i.e. 2 phonemes and not 3).

I've a few queries about a few examples in the data:

SWEDISH Word 30
bl~ud - Are the b and l really combined as one phoneme here?  In SWEDISH2, the word is simply blud.

ADYGHE-2 Word 81
w ~ 3Xw ~ a - There is only one symbol before the ~ , so what is the word-initial 'w' here to combine with?  There are a few other similar examples of this in the dataset. These are all marked by a  << ~ >> sequence in the segments column ("Normal" combinations such as kw~ don't contain this sequence in the segments column).  Combinations such as word initial w~, h~, and also TS~, kw~ y~ all contain this << ~ >> in the segments columns (the latter seemingly a palatalisation of a labialised k, and thus distinct from kwy$).

How are the others to be interpreted?

**Comment by LinguList** [comment]
It is interesting to note that we dind about 900 dostinct segments in asjp, although there are seemingly strict rules for combination.

**Comment by LinguList** [comment]
This was never realky discussed nor are there guidelines, but many contributors interpreted the symbols to express things that were mot supposed to ever be expressed. You also find tr as a combined sound expressing a retroflex t.

**Comment by LinguList** [comment]
So what happened,  to answer your question, is not clear. It is due to individual decisions by individual contributors. Impossible to find out the details. But Søren may be able to indicate how procedures for correction of data are supposed to take place.

**Comment by LinguList** [comment]
From our side, as the ones who help to convert the data to cldf format, we can probably help to show alls variation in the sounds.
