### ISSUE TITLE
Update languages.tsv

### ISSUE THREAD

**Issue by chrzyki** [lexibank/asjp#14]
#13 adds more mappings but is missing some columns that can be filled automatically with Glottolog.

**Comment by chrzyki** [comment]
Also: add Proto-languages to family glottocodes.

**Comment by SimonGreenhill** [comment]
Hi @chrzyki -- how did we get on with this?

**Comment by chrzyki** [comment]
Hey @SimonGreenhill, I've added more proto-languages in this PR: https://github.com/lexibank/asjp/commit/a35247270fca5fe520cb830770acd55c777a2479 (those that could be done reasonably well automatically). I'll have another go at more manual mappings today.

/edit: Not PR, commit, sorry.

**Comment by SimonGreenhill** [comment]
thanks @chrzyki just had a look at the outstanding ones, it looks like most are protolanguages which are probably not worth chasing down anymore, happy to close this.

**Comment by chrzyki** [comment]
Alright, thanks for checking!
