### ISSUE TITLE
Rename seraiki as Saraiki

### ISSUE THREAD

**Issue by mpQadir** [lexibank/asjp#16]
In site, https://asjp.clld.org/languages/SERAIKI The name of language is written as Saraiki. But its actual name is Saraiki. So it may be corrected please.
2. Also population be corrected please.
3.  Also map be corrected please

**Comment by xrotwang** [comment]
The ASJP website serves the latest released version of [lexibank/asjp](https://github.com/lexibank/asjp/releases). There's a new release coming up later this month which may fix the name. Speaker numbers and geographic coordinates are pulled in from other sources, though, so we won't be able to change these.
